---
name: pygskin

channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.15.0
  - humanfriendly=4.18
  - jupyter=1.0.0
  - pip
  - pip:
    - pytest-watch==4.2.0
    - pandas==1.4.0
    - datetime==4.4
    - pytest-bdd==5.0.0
    - sodapy==2.1.0